// object constructor
function card(name, imgSrc, alt) {
  this.name = name;
  this.imgSrc = imgSrc;
  this.alt = alt;
}

var deck = [
  new card("The Fool", "cardsRWS/0_theFool.jpeg", "The Fool"),
  new card("The Magician", "cardsRWS/1_theMagician.jpeg", "The Magician"),
  new card("The High Priestess", "cardsRWS/2_theHighPriestess.jpeg", "The High Priestess"),
  new card("The Empress", "cardsRWS/3_theEmpress.jpeg", "The Empress"),
  new card("The Emperor", "cardsRWS/4_theEmperor.jpeg", "The Emperor"),
  new card("The Hierophant", "cardsRWS/5_theHierophant.jpeg", "The Hierophant"),
  new card("The Lovers", "cardsRWS/6_theLovers.jpeg", "The Lovers"),
  new card("The Chariot", "cardsRWS/7_theChariot.jpeg", "The Chariot"),
  new card("Strength", "cardsRWS/8_Strength.jpeg", "Strength"),
  new card("The Hermit", "cardsRWS/9_theHermit.jpeg", "The Hermit"),
  new card("Wheel of Fortune", "cardsRWS/10_wheelOfFortune.jpeg", "Wheel of Fortune"),
  new card("Justice", "cardsRWS/11_Justice.jpeg", "Justice"),
  new card("The Hanged Man", "cardsRWS/12_theHangedMan.jpeg", "The Hanged Man"),
  new card("Death", "cardsRWS/13_Death.jpeg", "Death"),
  new card("Temperance", "cardsRWS/14_Temperance.jpeg", "Temperance"),
  new card("The Devil", "cardsRWS/15_theDevil.jpeg", "The Devil"),
  new card("The Tower", "cardsRWS/16_theTower.jpeg", "The Tower"),
  new card("The Star", "cardsRWS/17_theStar.jpeg", "The Star"),
  new card("The Moon", "cardsRWS/18_theMoon.jpeg", "The Moon"),
  new card("The Sun", "cardsRWS/19_theSun.jpeg", "The Sun"),
  new card("Judgment", "cardsRWS/20_Judgment.jpeg", "Judgment"),
  new card("The World", "cardsRWS/21_theWorld.jpeg", "The World"),
  new card("Ace of Wands", "cardsRWS/W_AceofWands.jpeg", "Ace of Wands"),
  new card("Two of Wands", "cardsRWS/W_2ofWands.jpeg", "Two of Wands"),
  new card("Three of Wands", "cardsRWS/W_3ofWands.jpeg", "Three of Wands"),
  new card("Four of Wands", "cardsRWS/W_4ofWands.jpeg", "Four of Wands"),
  new card("Five of Wands", "cardsRWS/W_5ofWands.jpeg", "Five of Wands"),
  new card("Six of Wands", "cardsRWS/W_6ofWands.jpeg", "Six of Wands"),
  new card("Seven of Wands", "cardsRWS/W_7ofWands.jpeg", "Seven of Wands"),
  new card("Eight of Wands", "cardsRWS/W_8ofWands.jpeg", "Eight of Wands"),
  new card("Nine of Wands", "cardsRWS/W_9ofWands.jpeg", "Nine of Wands"),
  new card("Ten of Wands", "cardsRWS/W_10ofWands.jpeg", "Ten of Wands"),
  new card("Page of Wands", "cardsRWS/W_PageofWands.jpeg", "Page of Wands"),
  new card("Knight of Wands", "cardsRWS/W_KnightofWands.jpeg", "Knight of Wands"),
  new card("Queen of Wands", "cardsRWS/W_QueenofWands.jpeg", "Queen of Wands"),
  new card("King of Wands", "cardsRWS/W_KingofWands.jpeg", "King of Wands"),
  new card("Ace of Cups", "cardsRWS/C_AceofCups.jpeg", "Ace of Cups"),
  new card("Two of Cups", "cardsRWS/C_2ofCups.jpeg", "Two of Cups"),
  new card("Three of Cups", "cardsRWS/C_3ofCups.jpeg", "Three of Cups"),
  new card("Four of Cups", "cardsRWS/C_4ofCups.jpeg", "Four of Cups"),
  new card("Five of Cups", "cardsRWS/C_5ofCups.jpeg", "Five of Cups"),
  new card("Six of Cups", "cardsRWS/C_6ofCups.jpeg", "Six of Cups"),
  new card("Seven of Cups", "cardsRWS/C_7ofCups.jpeg", "Seven of Cups"),
  new card("Eight of Cups", "cardsRWS/C_8ofCups.jpeg", "Eight of Cups"),
  new card("Nine of Cups", "cardsRWS/C_9ofCups.jpeg", "Nine of Cups"),
  new card("Ten of Cups", "cardsRWS/C_10ofCups.jpeg", "Ten of Cups"),
  new card("Page of Cups", "cardsRWS/C_PageofCups.jpeg", "Page of Cups"),
  new card("Knight of Cups", "cardsRWS/C_KnightofCups.jpeg", "Knight of Cups"),
  new card("Queen of Cups", "cardsRWS/C_QueenofCups.jpeg", "Queen of Cups"),
  new card("King of Cups", "cardsRWS/C_KingofCups.jpeg", "King of Cups"),
  new card("Ace of Swords", "cardsRWS/S_AceofSwords.jpeg", "Ace of Swords"),
  new card("Two of Swords", "cardsRWS/S_2ofSwords.jpeg", "Two of Swords"),
  new card("Three of Swords", "cardsRWS/S_3ofSwords.jpeg", "Three of Swords"),
  new card("Four of Swords", "cardsRWS/S_4ofSwords.jpeg", "Four of Swords"),
  new card("Five of Swords", "cardsRWS/S_5ofSwords.jpeg", "Five of Swords"),
  new card("Six of Swords", "cardsRWS/S_6ofSwords.jpeg", "Six of Swords"),
  new card("Seven of Swords", "cardsRWS/S_7ofSwords.jpeg", "Seven of Swords"),
  new card("Eight of Swords", "cardsRWS/S_8ofSwords.jpeg", "Eight of Swords"),
  new card("Nine of Swords", "cardsRWS/S_9ofSwords.jpeg", "Nine of Swords"),
  new card("Ten of Swords", "cardsRWS/S_10ofSwords.jpeg", "Ten of Swords"),
  new card("Page of Swords", "cardsRWS/S_PageofSwords.jpeg", "Page of Swords"),
  new card("Knight of Swords", "cardsRWS/S_KnightofSwords.jpeg", "Knight of Swords"),
  new card("Queen of Swords", "cardsRWS/S_QueenofSwords.jpeg", "Queen of Swords"),
  new card("King of Swords", "cardsRWS/S_KingofSwords.jpeg", "King of Swords"),
  new card("Ace of Pentacles", "cardsRWS/P_AceofPentacles.jpeg", "Ace of Pentacles"),
  new card("Two of Pentacles", "cardsRWS/P_2ofPentacles.jpeg", "Two of Pentacles"),
  new card("Three of Pentacles", "cardsRWS/P_3ofPentacles.jpeg", "Three of Pentacles"),
  new card("Four of Pentacles", "cardsRWS/P_4ofPentacles.jpeg", "Four of Pentacles"),
  new card("Five of Pentacles", "cardsRWS/P_5ofPentacles.jpeg", "Five of Pentacles"),
  new card("Six of Pentacles", "cardsRWS/P_6ofPentacles.jpeg", "Six of Pentacles"),
  new card("Seven of Pentacles", "cardsRWS/P_7ofPentacles.jpeg", "Seven of Pentacles"),
  new card("Eight of Pentacles", "cardsRWS/P_8ofPentacles.jpeg", "Eight of Pentacles"),
  new card("Nine of Pentacles", "cardsRWS/P_9ofPentacles.jpeg", "Nine of Pentacles"),
  new card("Ten of Pentacles", "cardsRWS/P_10ofPentacles.jpeg", "Ten of Pentacles"),
  new card("Page of Pentacles", "cardsRWS/P_PageofPentacles.jpeg", "Page of Pentacles"),
  new card("Knight of Pentacles", "cardsRWS/P_KnightofPentacles.jpeg", "Knight of Pentacles"),
  new card("Queen of Pentacles", "cardsRWS/P_QueenofPentacles.jpeg", "Queen of Pentacles"),
  new card("King of Pentacles", "cardsRWS/P_KingofPentacles.jpeg", "King of Pentacles"),
];




// Cards from https://en.wikipedia.org/wiki/Rider-Waite_tarot_deck
// Authorship: Arthur Edward Waite, Artist: Pamela Colman Smith.
// Waite was the copyright holder and he died in 1942. His renwed copyright lasted until 1966, at which point the deck became part of the public domain.